# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e564030bc5558d28b255c54f703b7459befed8348b8e8080c65fbb13545b05a48eb206533ebec2ba8767d973f375c1794780c1882397c4003a382f30c54bf2e0

test:
  secret_key_base: fa885a8bccb09669d9abbde7b3e9d276ce4f546948e9dd79797e846cd9495960f447d1653e2fd724e6d3e5c0180a068ff5217ba4d6e1ca8e56c670ed54477b75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
